### ISSUE TITLE
PT-P700 works with changed initialization sequence

### ISSUE THREAD

**Issue by tingox** [clarkewd/ptouch-print#2]
I can confirm that the PT-P700 works if you change to the correct sequence for "Switch dynamic command mode" for this model.
in src/libptouch.c I changed the ptdevs[] entry for PT-P700 to
`{0x04f9, 0x2061, "PT-P700", 128, FLAG_RASTER_PACKBITS},`
and in function ptouch_rasterstart(ptouch_dev ptdev) I changed the init sequence to
`char cmd[] = "\x1b\x69\x61\x01";`
recompile, test
first '--info' (this worked before the change too)
```
tingo@kg-vm4:~/work/Brother/clarkewd/ptouch-print$ ./ptouch-print --info
PT-P700 found on USB bus 10, device 3
maximum printing width for this tape is 128px
media type = 01
media width = 24 mm
tape color = 01
text color = 08
error = 0000
```
then print
```
tingo@kg-vm4:~/work/Brother/clarkewd/ptouch-print$ ./ptouch-print --text "PT-P700 test"
PT-P700 found on USB bus 10, device 3
choosing font size=125
created new img width dimensionx 1025 * 128
copied part 2
enable PackBits mode

```
it works! Since I had a 24mm tape in, I got a large test print :-)

**Comment by clarkewd** [comment]
This is a great find! I've written Dominic to see if we can get this incorporated. Thank you!

**Comment by clarkewd** [comment]
Dominic has [added the changes you suggested into the code](https://github.com/clarkewd/ptouch-print/commit/98541a6f6148633e057a3a6d11e0155d2cb5438b). I've compiled and tested on my PT-P700 and it worked well for me. Thank you for your contribution!

**Comment by tingox** [comment]
Yes. works here with the changed code too. Thanks for helping to fix this!
